#1. Create a class called TopicBuilder to generate consistent UNS-style MQTT topics.
#Goal: Encapsulate MQTT topic naming rules inside a class so the rest of your code can 
# call one clean interface. 
#--------------Requirements: -------------------------------------------
""" 
Attributes (instance data)
site: str
line: str
cell: str
These represent the fixed “location” part of the topic.

Methods:
1) build(tag) 
Return a topic string in this format:
site/line/cell/tag
Normalization rules (apply to every segment, including tag):
-   convert to lowercase
-   trim spaces around the text
-   replace internal spaces " " with "_"

2) with_cell(new_cell) 
Update the object's cell attribute with new_cell (also normalized).
This simulates moving the same logic to a different cell without creating a new instance.
"""
print("------------------------Exercise 1: Topic Builder --------------------------\n")

class TopicBuilder: 
    """ Generate  consistent UNS-style MQTT topics"""
    def __init__(self, site: str, line: str, cell: str):
        """ Initialize a TopicBuilder with normalized UNS topic segments (site, line, cell).
All segments are stored in a consistent format: lowercase, trimmed, and with
internal spaces replaced by underscores."""
        self.site = site
        self.line = line
        self.cell = cell
        #Normalize segments:
        self.site = self.site.lower().strip().replace(" ", "_")
        self.line = self.line.lower().strip().replace(" ", "_")
        self.cell = self.cell.lower().strip().replace(" ", "_") 

    def build(self, tag: str) -> str:
        """ 
        Build and return a normalized UNS-style MQTT topic: site/line/cell/tag.
        The tag is normalized (lowercase, trimmed, spaces -> '_') before joining.
        """
        tag = tag.lower().strip().replace(" ", "_")
        temporal_list: list[str] = [self.site, self.line, self.cell, tag]
        return  "/".join(temporal_list)
    
    def with_cell(self, new_cell: str) -> None:
        """ 
        Update the object's cell attribute with new_cell (also normalized).
        """
        self.cell = new_cell.lower().strip().replace(" ", "_")
        

#2. AlarmEvent + AlarmPolicy 
# Create two classes:
#AlarmEvent 
""" Attributes
    code: str
    severity: int
    ts: int
    source_topic: str
Methods
    is_critical() -> bool
 Return True if severity is above your chosen threshold.
    summary() -> str
 Return a short string summary of the alarm.
"""
#AlarmPolicy
""" Attributes
    min_severity: int
    blocked_codes: set[str]
Methods
    is_actionable(alarm: AlarmEvent) -> bool
 Return True only if the alarm passes the policy rules.
"""
#Goal: Separate data (alarm event) from decision logic (policy), without using inheritance.

print("----------------------Exercise 2: AlarmEvent + AlarmPolicy  -------------------------\n")

class AlarmEvent: 
    """Represents an alarm generated by an IIoT device or system."""

    def __init__(self, code: str, severity: int, ts: int, source_topic: str):
        self.code = code
        self.severity = severity
        self.ts = ts
        self.source_topic = source_topic
    
    def is_critical(self) -> bool:
        """Return True if the alarm severity is above the critical threshold. """
        return self.severity > 3

    def summary(self) -> str:
        """ Return a short text summary of the alarm."""
        return f"Alarm: {self.code} | sev={self.severity} | ts={self.ts} | source={self.source_topic}"

class AlarmPolicy:
    """Defines rules to decide if an alarm requires action or not."""

    def __init__(self, min_severity: int, blocked_codes: set[str]):
        """Initialize the policy with a minimum severity and blocked alarm codes."""
        self.min_severity = min_severity
        self.blocked_codes = blocked_codes
    
    def is_actionable(self, alarm: AlarmEvent) -> bool:
        """Return True if the alarm passes the policy rules."""
        if alarm.severity >= self.min_severity and alarm.code not in self.blocked_codes:
            return True
        else:
            return False
        

#3. ShiftReport: Create a class called ShiftReport to store production data and calculate simple KPIs.
""" 
---Attributes:
shift: str
approved: int
rejected: int
warnings: list[str] — starts empty
---Methods
total() -> int
scrap_rate() -> float
add_warning(msg: str) -> None
as_dict() -> dict
---Rules
If total production is zero, scrap_rate() must return 0.0
In that zero-total case, also add a warning to warnings
Do not print inside methods
---Goal
Practice storing state and encapsulating business logic inside methods.
"""

print("----------------------Exercise 3: ShiftReport  -------------------------\n")

class ShiftReport:

    def __init__(self, shift: str, approved: int, rejected: int):
        self.shift = shift
        self.approved = approved
        self.rejected =  rejected
        self.warnings: list[str] = []

    def total(self) -> int:
        """ Calculate the total of produced units"""
        return self.approved + self.rejected

    def scrap_rate(self) -> float:
        """ Calculate the scrape rate of the total produced units"""
        total_units = self.total() #Create local var

        if total_units == 0:
            self.add_warning("Cannot calculate  scrap rate")
            return 0.0
        
        else: return round(self.rejected / total_units * 100, 2)

    def add_warning(self, msg: str) -> None:
        """This function adds a warning, a string to the warnings list."""
        self.warnings.append(msg)

    def as_dict(self) -> dict:
        """ Return the report data as a dictionary"""
        return {
            'shift': self.shift,
            'approved': self.approved,
            'rejected': self.rejected,
            'scrap_rate': self.scrap_rate(),
            'warnings': self.warnings
        }
test_shift_report = ShiftReport("morning", 1500000, 20000)
#Tests:
#Attributes
print(test_shift_report.shift)
print(test_shift_report.approved)
print(test_shift_report.rejected)
#Methods
print(test_shift_report.total())
print(test_shift_report.scrap_rate())

test_shift_report.add_warning("check rejected units")
print(test_shift_report.warnings)

print(test_shift_report.as_dict())
